### ISSUE TITLE
ESlint: Error while loading rule

### ISSUE THREAD

**Issue by rexkenley** [mdx-js/eslint-mdx#421] opened 2022-08-31 19:48 UTC
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.0.2

### Steps to reproduce

1. Clone the repo https://github.com/rexkenley/next-storybook
2.  Load any *.mdx file in vs-code
3.  You should get this error
![image](https://user-images.githubusercontent.com/10548251/187768607-68c1afad-4335-4236-9e1e-da41dce5e00f.png)

### Expected behavior

It should not complain about @typescript-eslint rules since I have an override for mdx

![image](https://user-images.githubusercontent.com/10548251/187768859-b608af4c-cd46-4d7a-a2da-9249394d5f36.png)

### Actual behavior

Displays this error

![image](https://user-images.githubusercontent.com/10548251/187768973-566e600a-933d-47a5-8d5b-39d46513cbdb.png)

### Runtime

Node v16

### Package manager

npm v8

### OS

Windows

### Build and bundle tools

webpack

**Comment by JounQin** [comment] 2022-08-31 20:59
Duplicate of https://github.com/mdx-js/eslint-mdx/issues/251#issuecomment-963837780

Always use overrides for every kind of files.

**Closed by JounQin** 2022-08-31 20:59 UTC

**Comment by rexkenley** [comment] 2022-09-01 01:30
@JounQin 

So in essence the extends should be "empty"?
