### ISSUE TITLE
Can't disable a rule with mdx-js/eslint-mdx and remake-lint

### ISSUE THREAD

**Issue by DanielFerrariR** [mdx-js/eslint-mdx#205] opened 2020-05-21 16:47 UTC
Can't disable remake-lint rules while using it with mdx-js/eslint-mdx (on a .md file). Tried:

```
<!--lint disable no-duplicate-headings-->
// eslint-disable-next-line mdx/remark
/ eslint-disable mdx/remark /
```

I can disable mdx rules in .mdx files just fine, but it doesn't work for .md ones.

Also, seems pretty bad to have to reload my vscode to update disabled rules from .remarkrc file. Is there any better way to use these rules with eslint?

package.json
```
"eslint": "v7.0.0",
"eslint-plugin-mdx": "^1.6.9",
"remark-preset-lint-consistent": "^3.0.0",
"remark-preset-lint-markdown-style-guide": "^3.0.0",
"remark-preset-lint-recommended": "^4.0.0",
"remark-preset-prettier": "^0.4.0",
```

.eslintrc
```
"overrides": [
  {
    "files": "**/*.+(md|mdx)",
    "extends": ["plugin:mdx/recommended"]
   }
]
```

.remarkrc
```
module.exports = {
  plugins: [
    'preset-lint-consistent',
    'preset-lint-markdown-style-guide',
    'preset-lint-recommended',
    'preset-prettier'
  ]
}
```

**Comment by JounQin** [comment] 2020-05-24 10:12
@DanielFerrariR Please provide a minimal and runnable reproduction like a GitHub repository with https://www.gitpod.io/.

**Comment by JounQin** [comment] 2020-05-24 10:21
`You’ll need the blank lines between comments and other nodes!` (from [remark-lint](https://github.com/remarkjs/remark-lint))

Did you try to add a blank line after `<!--lint disable no-duplicate-headings-->`?

**Comment by DanielFerrariR** [comment] 2020-05-25 14:23
https://github.com/DanielFerrariR/mdx-eslint-example

Couldn't make eslint work on gitpod.io. Maybe because extensions is on beta phase there.

**Comment by JounQin** [comment] 2020-05-26 04:33
@DanielFerrariR Thanks for reporting, and I can reproduce it locally now.

But it seems a bug of `remark` API itself, because I tried to call the API manually, the warning is always there:

```md
<!-- README.md -->
<!--lint disable no-literal-urls-->

### Code Splitting

This section has moved here: https://facebook.github.io/create-react-app/docs/code-splitting
```

```js
const fs = require('fs')

const remark = require('remark')
const noLiteralUrls = require('remark-lint-no-literal-urls')
const report = require('vfile-reporter')

const file = remark().use(noLiteralUrls).processSync(fs.readFileSync('README.md', 'utf8'))
console.log(report(file))
```

```log
  5:30-5:93  warning  Don’t use literal URLs without angle brackets  no-literal-urls  remark-lint

⚠ 1 warning
```

But if I use `remark-cli` directly with `yarn remark README.md`, there will be no issue anymore.

@wooorm Any idea?

Maybe related: https://github.com/remarkjs/remark-lint/issues/47

**Comment by JounQin** [comment] 2020-05-26 05:03
OK, I found out that whenever I add `remark-mdx` into `remarkProcessor` at https://github.com/mdx-js/eslint-mdx/blob/master/packages/eslint-plugin-mdx/src/rules/helper.ts#L81, there will be warnings, if I remove `.use(remarkMdx)` there, it will just work as expected.

So it should be an issue of `remark-mdx`? @wooorm 

What means `disable` comments parsed by `remark-mdx` will stop working.

**Comment by wooorm** [comment] 2020-05-26 07:01
Weird. For a quick fix for now, adding this plugin right after remark-mdx should do the trick @JounQin: https://github.com/mdx-js/mdx/blob/master/packages/mdx/md-ast-to-mdx-ast.js

That’s a step MDX takes right before applying `remarkPlugins`, which it’s doing outside of the unified flow unfortunately.

In the v2 branch, I removed that step: https://github.com/mdx-js/mdx/tree/next/packages/mdx

**Comment by JounQin** [comment] 2020-05-26 13:15
@wooorm I don't know whether I understand correctly but I tried like following:

```js
const fs = require('fs')

const toMDXAST = require('@mdx-js/mdx/md-ast-to-mdx-ast')
const remark = require('remark')
const remarkMdx = require('remark-mdx')
const remarkLint = require('remark-lint')
const noLiteralUrls = require('remark-lint-no-literal-urls')
const report = require('vfile-reporter')

const file = remark()
  .use(remarkLint)
  .use(noLiteralUrls)
  .use(remarkMdx)
  .use(toMDXAST)
  .processSync(fs.readFileSync('README.md', 'utf8'))

console.log(report(file))
```

There will be a fetal error:

```log
Missing compiler for node of type `comment`: `[object Object]`
```

**Comment by wooorm** [comment] 2020-05-26 13:26
Gosh, that’s a pity.

**Comment by JounQin** [comment] 2020-08-05 06:58
@wooorm Please help to publish a new release, it should be fixed.

**Closed by JounQin** 2020-08-05 06:58 UTC
Labels: 🙆 status/confirmed

**Comment by wooorm** [comment] 2020-08-05 09:00
Published!

Weird: I have a `GH_TOKEN` set up (echo $GH_TOKEN had the correct token as output) but `yarn deploy` didn’t pick up on it 🤔
