### ISSUE TITLE
Unable to lint MDX components in `2.0.0-next.2`

### ISSUE THREAD

**Issue by B2o5T** [mdx-js/eslint-mdx#391] opened 2022-05-07 11:49 UTC
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.0.0-next.2

### Steps to reproduce

```js
module.exports = {
  overrides: [
    {
      files: '*.md{,x}',
      parser: 'eslint-mdx',
      processor: 'mdx/remark',
      plugins: ['mdx'],
      settings: {
        'mdx/code-blocks': true
      }
    },
    {
      files: ['*.md{,x}', '*.{j,t}s{,x}'],
      extends: 'plugin:react/recommended'
    }
  ]
}
```

```mdx
# Hello world

\```js
<Foo />
\```

<Foo />

\```jsx
<Foo />
\```
```

### Expected behavior

```
/Users/dimitri/Desktop/mdx-repro/test.mdx
   7:1  error  'React' must be in scope when using JSX  react/react-in-jsx-scope
   7:2  error  'Foo' is not defined                     react/jsx-no-undef
   4:1  error  'React' must be in scope when using JSX  react/react-in-jsx-scope
   4:2  error  'Foo' is not defined                     react/jsx-no-undef
  10:1  error  'React' must be in scope when using JSX  react/react-in-jsx-scope
  10:2  error  'Foo' is not defined                     react/jsx-no-undef

✖ 6 problems (6 errors, 0 warnings)
```

### Actual behavior

```
   4:1  error  'React' must be in scope when using JSX  react/react-in-jsx-scope
   4:2  error  'Foo' is not defined                     react/jsx-no-undef
  10:1  error  'React' must be in scope when using JSX  react/react-in-jsx-scope
  10:2  error  'Foo' is not defined                     react/jsx-no-undef

✖ 4 problems (4 errors, 0 warnings)
```

**Comment by JounQin** [comment] 2022-05-07 13:39
Should be related to https://github.com/mdx-js/eslint-mdx/issues/384#issuecomment-1110737802, waiting for micromark/micromark-extension-mdx-expression#4.

**Comment by wooorm** [comment] 2022-05-11 10:29
micromark is released!

**Comment by JounQin** [comment] 2022-05-11 10:56
I created #393 to make sure, after upgrading `micromark-util-events-to-acorn`, it works as expected.

@B2o5T Please upgrade it by yourself by deleting `yarn.lock`, etc.

**Comment by B2o5T** [comment] 2022-05-11 11:56
@JounQin upgraded but the issue was not solved even on the latest `micromark-util-events-to-acorn@1.1.0`

info from yarn.lock
```
micromark-util-events-to-acorn@^1.0.0:
  version "1.1.0"
  resolved "https://registry.yarnpkg.com/micromark-util-events-to-acorn/-/micromark-util-events-to-acorn-1.1.0.tgz#9891638e201c266484d0af7cd2505d208f73db9d"
  integrity sha512-hB8HzidNt/Us5q2BvqXj8eeEm0U9rRfnZxcA9T65JRUMAY4MbfJRAFm7m9fXMAdSHJiVPmajsp8/rp6/FlHL8A==
  dependencies:
    "@types/acorn" "^4.0.0"
    "@types/estree" "^0.0.51"
    estree-util-visit "^1.0.0"
    micromark-util-types "^1.0.0"
    uvu "^0.5.0"
    vfile-location "^4.0.0"
    vfile-message "^3.0.0"
```

**Comment by JounQin** [comment] 2022-05-11 12:03
Oh, should also be related to https://github.com/mdx-js/eslint-mdx/issues/384#issuecomment-1123625050

The jsx tokens are not available for now.

**Comment by JounQin** [comment] 2022-05-13 14:21
@B2o5T Besides, the two rules are disabled for mdx content in the recommended config at https://github.com/mdx-js/eslint-mdx/blob/master/packages/eslint-plugin-mdx/src/configs/overrides.ts#L23-L35, that's why I can't reproduce it at #393

**Comment by JounQin** [comment] 2022-05-14 05:55
Close because duplicate of #384

**Closed by JounQin** 2022-05-14 05:55 UTC

**Comment by JounQin** [comment] 2022-05-14 12:05
@B2o5T 

Please try:

```sh
# yarn 1
yarn add https://pkg.csb.dev/mdx-js/eslint-mdx/commit/cc2cd6c2/eslint-mdx https://pkg.csb.dev/mdx-js/eslint-mdx/commit/cc2cd6c2/eslint-plugin-mdx
# yarn 2, 3
yarn add eslint-mdx@https://pkg.csb.dev/mdx-js/eslint-mdx/commit/cc2cd6c2/eslint-mdx/_pkg.tgz eslint-plugin-mdx@https://pkg.csb.dev/mdx-js/eslint-mdx/commit/cc2cd6c2/eslint-plugin-mdx/_pkg.tgz
# npm
npm i https://pkg.csb.dev/mdx-js/eslint-mdx/commit/cc2cd6c2/eslint-mdx https://pkg.csb.dev/mdx-js/eslint-mdx/commit/cc2cd6c2/eslint-plugin-mdx
```

**Comment by B2o5T** [comment] 2022-05-14 12:14
@JounQin Thank you! it's works 😍
```
/Users/dimitri/Desktop/mdx-repro/test.mdx
   4:1  error  'React' must be in scope when using JSX  react/react-in-jsx-scope
   4:2  error  'Foo' is not defined                     react/jsx-no-undef
   7:1  error  'React' must be in scope when using JSX  react/react-in-jsx-scope
   7:2  error  'Foo' is not defined                     react/jsx-no-undef
  10:1  error  'React' must be in scope when using JSX  react/react-in-jsx-scope
  10:2  error  'Foo' is not defined                     react/jsx-no-undef

✖ 6 problems (6 errors, 0 warnings)
```
